twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - bootstrap_4_layout.html.twig
    globals:
      bishopstitle: 'Die Patriarchen, Erzbischöfe, Bischöfe, Weihbischöfe und weitere diözesane Leitungspersonen des Alten Reiches (nach Erwin Gatz)'
      diocesestitle: 'Die Erzbistümer und Bistümer des Alten Reiches'
      

