twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        url_geonames: https://www.geonames.org/
        url_gs_bios: http://personendatenbank.germania-sacra.de/books/findpage/
        protocol: https

when@test:
    twig:
        strict_variables: true
