#index:
#    path: /
#    controller: App\Controller\DefaultController::index

wiag_version:
  path: /version
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'start/version.html.twig'
